### ISSUE TITLE
这里写错了, 然后日志无法关闭

### ISSUE THREAD

**Issue by badboy-tian** [Javen205/TNWX#35]
https://github.com/Javen205/TNWX/blob/master/packages/accesstoken/src/ApiConfigKit.ts

```
public static isDevMode(): boolean {
    return this.devMode
  }
```
这里devMode是static类型的. 但是设置无效 每次都会把日志打印出来, 希望修改下, 谢谢

**Comment by Javen205** [comment]
已经处理了
