### ISSUE TITLE
Cannot find module './entity/QyMiniProgramNoticeMsg'.

### ISSUE THREAD

**Issue by BingxingXu** [Javen205/TNWX#4]
build报错。mac下没有报错，生产环境ubuntu build失败。使用过cnpm yarn npm 分别安装依赖都不行。

使用的nest 

node_modules/_@tnwx_wxcp@2.1.2@@tnwx/wxcp/dist/index.d.ts:13:61 - error TS2307: Cannot find module './entity/QyMiniProgramNoticeMsg'.

13 export { QyMiniProgramNoticeMsg, QyMiniprogram, QyKv } from './entity/QyMiniProgramNoticeMsg';
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Javen205** [comment]
`yarn add tnwx`  我这边测试是正常的。

你尝试移除 tnwx 再添加试试

**Comment by Javen205** [comment]
解决方案 `QyMiniProgramNoticeMsg`  中的「n」改成大写即 ` QyMiNiProgramNoticeMsg`
