### ISSUE TITLE
服务号的订阅通知

### ISSUE THREAD

**Issue by icemanpro** [Javen205/TNWX#42]
### 版本信息

- 当前版本:
- 操作系统:
- 复现操作：

### 报错信息 （注意格式化）

```
这里粘贴代码或者、日志
```

### 问题描述（包括回显步骤、截图 ）

原模板消息4月30日关闭，现在TNWX支持订阅消息吗？代码中没看到订阅消息的请求地址。

**Comment by Javen205** [comment]
MiniSubscribeMsgApi

**Comment by icemanpro** [comment]
服务号中的发送订阅通知的地址是https://api.weixin.qq.com/cgi-bin/message/subscribe/bizsend?access_token=ACCESS_TOKEN 与小程序中的不一样。

**Comment by Javen205** [comment]
> 服务号中的发送订阅通知的地址是https://api.weixin.qq.com/cgi-bin/message/subscribe/bizsend?access_token=ACCESS_TOKEN 与小程序中的不一样。

2.5.5 版本中已实现   ComSubscribeMsgApi
